name: Publish MSSQLClient Mcp Server to Dockerhub

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Only trigger on tags with format like 1.2.3

jobs:
  container-build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Update version in project file
        run: |
          # Extract the version from the tag
          VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "Updating project version to $VERSION"
          
          # Use XML tool to update the version in the project file
          # This updates AssemblyVersion, FileVersion, and Version properties
          sed -i \
            -e "s/<AssemblyVersion>.*<\/AssemblyVersion>/<AssemblyVersion>$VERSION<\/AssemblyVersion>/g" \
            -e "s/<FileVersion>.*<\/FileVersion>/<FileVersion>$VERSION<\/FileVersion>/g" \
            -e "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/g" \
            src/Core.Infrastructure.McpServer/Core.Infrastructure.McpServer.csproj
          
          # Show the updated file for verification
          cat src/Core.Infrastructure.McpServer/Core.Infrastructure.McpServer.csproj
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Core.Infrastructure.McpServer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_CONFIGURATION=Release
          tags: |
            aadversteeg/mssqlclient-mcp-server:${{ steps.get_version.outputs.VERSION }}
            aadversteeg/mssqlclient-mcp-server:latest
